DROP DATABASE IF EXISTS spring_pj;

CREATE DATABASE IF NOT EXISTS spring_pj;

GRANT CREATE, ALTER, INSERT, UPDATE, DELETE, DROP, SELECT 
ON anytimemeet.* TO 'john'@'localhost' IDENTIFIED BY '1234567';
